### ISSUE TITLE
Check for module candidates.

### ISSUE THREAD

**Issue by FatmanUK** [FatmanUK/k3s_playground#19]
It's a smaller set than I thought it'd be.

**Comment by athajaerel** [comment]
k3s_master_post:
```
- name: 'Install manifests'
  register: 'reg_install_manifests'
  when: 'is_primary'
  vars:
    path: '{{ (manifests_path_prefix, item) | path_join }}'
  loop: '{{ manifests }}'
  failed_when:
    - 'reg_install_manifests.rc != 0'
    - 'e_manifest_already not in reg_install_manifests.stderr'
  command:
    argv:
      - '/usr/local/bin/kubectl'
      - 'create'
      - '-f'
      - '{{ path }}'

# seems like the next task might be failing before the containers register as
# existing --- mitigate with a pause
- name: 'Pause a few seconds for pods to be created'
  pause:
    seconds: 5

# module candidate? k3s_wait
# do repeat-until for long waits
# TODO: figure out failed_when condition for kubectl wait
- name: 'Wait for pods'
  when:
    - 'wait_selectors is defined'
    - 'wait_selectors'
  loop: '{{ wait_selectors }}'
  run_once: yes
  command:
    argv:
      - '/usr/local/bin/kubectl'
      - 'wait'
      - '--timeout={{ wait_timeout | default(default_wait_timeout) }}'
      - '--for=condition=Ready'
      - 'pod'
      - '-n'
      - '{{ namespace }}'
      - '--selector={{ item }}'
```

**Comment by athajaerel** [comment]
k3s_master_post:
```
# TODO: see what effect async and poll have on this task, maybe use it more
# TODO: figure out failed_when condition for kubectl wait
- name: 'Wait for all nodes'
  run_once: yes
  async: '{{ (nodes_timeout[:-1] | int) + 1 }}'
  poll: 1
  command:
    argv:
      - '/usr/local/bin/kubectl'
      - 'wait'
      - '--timeout={{ nodes_timeout }}'
      - '--for=condition=Ready'
      - 'node'
      - '{{ inventory_hostname }}.{{ domain }}'
```

**Comment by athajaerel** [comment]
k3s_prepare:
```
- name: 'Add shell to /etc/shells'
  loop: '{{ k3s_shells}}'
  lineinfile:
    path: '/etc/shells'
    line: '{{ item }}'
    insertafter: 'EOF'

# TODO: figure out failed_when for chsh
- name: 'Change ansible user shell'
  command:
    argv:
      - '{{ k3s_chsh }}'
      - '-s'
      - '{{ k3s_shells | first }}'
      - 'ansible'

- name: 'Write tmux config'
  loop:
    - '/home/ansible/.tmux.conf'
  template:
    src: '{{ item[1:] }}.j2'
    dest: '{{ item }}'
    owner: 'ansible'
    group: 'ansible'
    mode: '0644'
```
